### ISSUE TITLE
Support Chef Infra Client Version 17.6.18

### ISSUE THREAD

**Issue by jeremyciak** [mwrock/kitchen-nodes#44]
After a recent upgrade to Chef Infra Client Version `17.6.18`, my Chef Infra Client run is failing on the `Installing cookbook gem dependencies` step, resulting in the below error indicating that there is something amiss with our usage of the `kitchen-nodes` utility now that we have upgraded the Chef Infra Client Version. Previously, it worked fine with version `16.13.16`. Note that we are utilizing the `kitchen-nodes-scalp42` variety from @scalp42.

```
Installing ed25519 1.2.4 with native extensions
STDERR: Gem::Ext::BuildError: ERROR: Failed to build gem native extension.



current directory:

C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ed25519-1.2.4/ext/ed25519_ref10

C:/opscode/chef/embedded/bin/ruby.exe -I C:/opscode/chef/embedded/lib/ruby/3.0.0

-r ./siteconf20211006-1952-ynh39v.rb extconf.rb

creating Makefile



current directory:

C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ed25519-1.2.4/ext/ed25519_ref10

make DESTDIR\= clean



current directory:

C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ed25519-1.2.4/ext/ed25519_ref10

make DESTDIR\=

generating ed25519_ref10-x64-mingw32.def

compiling ed25519_ref10.c

In file included from

c:/opscode/chef/embedded/include/ruby-3.0.0/ruby/missing.h:38:0,

from

c:/opscode/chef/embedded/include/ruby-3.0.0/ruby/defines.h:80,

from

c:/opscode/chef/embedded/include/ruby-3.0.0/ruby/ruby.h:23,

                 from c:/opscode/chef/embedded/include/ruby-3.0.0/ruby.h:38,

                 from ed25519_ref10.c:1:

c:\opscode\chef\embedded\mingw\bin\../lib/gcc/x86_64-w64-mingw32/4.7.2/../../../../x86_64-w64-mingw32/include/ieeefp.h:6:22:

fatal error: ansidecl.h: No such file or directory

compilation terminated.

make: *** [ed25519_ref10.o] Error 1



make failed, exit code 2



Gem files will remain installed in

C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/ed25519-1.2.4 for inspection.

Results logged to

C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/extensions/x64-mingw32/3.0.0/ed25519-1.2.4/gem_make.out



An error occurred while installing ed25519 (1.2.4), and Bundler cannot continue.

Make sure that `gem install ed25519 -v '1.2.4' --source 'https://rubygems.org/'`

succeeds before bundling.



In Gemfile:

  kitchen-nodes-scalp42 was resolved to 0.10.0, which depends on

    test-kitchen was resolved to 3.1.0, which depends on

      ed25519
```

**Comment by lamont-granquist** [comment]
That is a bug with the compilation environment on windows and the ed25519 gem, that has nothing to do with this gem directly.

It will get solved in the next release of chef-client which will bundle the ed25519 gem again.  I don't know what the workaround is in the meantime.

**Comment by jeremyciak** [comment]
@lamont-granquist do you know of the latest version of the Chef Infra Client where this bug is not present? Also, the only reason I'm pursuing jumping to a super recent version is due to the `remote_file` error I get currently due to the recent Let's Encrypt CA certificate expiration [as outlined in this post](https://www.zoocha.com/news/fixing-issues-multiple-servers-caused-recently-expired-root-certificate). If there is a way to resolve that issue without needing to upgrade the Chef Infra Client version then I can pursue that while this **ed25519** gem issue is resolved.

I also posted about all of this on the Chef Community Slack Channel:
https://chefcommunity.slack.com/archives/C0M1NGZE3/p1633541353177900

**Comment by lamont-granquist** [comment]
The latest version of chef-client fixes letsencrypt it does not fix the ed25519 problem.  

You need to manaually fix both c:/opscode/chef/embedded/ssl/certs/cacert.pem and c:/opscode/chef/embedded/ssl/cert.pem on windows.

**Comment by jeremyciak** [comment]
@lamont-granquist
How do I manually fix both of those on Windows? Can you offer any guidance on that? Or direct me to a post where someone has outlined those steps?

**Comment by jeremyciak** [comment]
For others' benefit, we added this code to a Chef recipe to fix the issue on our Windows machines:

```ruby
ca_cert_match = 'DST Root CA X3'

cacert_test = powershell_out(
  "
    $chefPath = 'C:\\opscode\\chef\\embedded'
    $certPath = [System.IO.Path]::Combine($chefPath,'ssl','certs','cacert.pem')
    $test1 = Select-String -Pattern '#{ca_cert_match}' -Path $certPath -Quiet
    $certPath = [System.IO.Path]::Combine($chefPath,'ssl','cert.pem')
    $test2 = Select-String -Pattern '#{ca_cert_match}' -Path $certPath -Quiet
    return ($test1 -or $test2)
  ").stdout.chomp().to_s.downcase

powershell_script 'Chef Client Fix cacert.pem' do
  code <<-EOH
  $dtStamp = (Get-Date).ToString('yyyyMMddHHmmss')
  $chefPath = 'C:\\opscode\\chef\\embedded'
  $chefBin = [System.IO.Path]::Combine($chefPath,'bin')
  $certPath = [System.IO.Path]::Combine($chefPath,'ssl','certs','cacert.pem')
  # create backup copy cacert.pem
  Copy-Item -Path "$certPath" -Destination "$($certPath).bak.$($dtStamp)"
  # remove expired cert from cacert.pem
  & "$($chefBin)\\sed.exe" -i '' '/#{ca_cert_match}/,/^$/ d' "$certPath"
  # create backup copy cert.pem
  $certPath = [System.IO.Path]::Combine($chefPath,'ssl','cert.pem')
  Copy-Item -Path "$certPath" -Destination "$($certPath).bak.$($dtStamp)"
  # remove expired cert from cert.pem
  & "$($chefBin)\\sed.exe" -i '' '/#{ca_cert_match}/,/^$/ d' "$certPath"
  EOH
  only_if { cacert_test == 'true' }
end
```
